name: linkedInScraper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - requests
  # - json
  - beautifulsoup4
  - time
  - openai
  - python-dotenv
  - black
  - pip
  - pandas
  - python-dotenv
  - py-mon

# To create and activate this environment, run:
# conda env create -f environment.yml
# conda activate linkedInScraper

# to update env file after adding a package, best to deactivate then update...
# conda env update --file environment.yml --prune


